FROM scratch

ADD 2d3bb1c59500dfd5c2b7d4c29b7484434c2c0a918922f41edccf78c3890f4e4a.tar.xz /
ADD 339f5fbedb3a77d2173a0abda81a6e0ce3622f2ae977ae2abf4ef422fb51f7bf.tar.xz /
ADD 659ad406a8b12835bf9e1f01792825d39c5361921fa7165614affbe1ce469175.tar.xz /
ADD 81072ae89ebc9f2c33954efc205bada1bea4435f2915fdd1c1310b7a5fd6ec19.tar.xz /
ADD c2de822782c92952c26a64715d419474cf2ca7b29bac3b35182c1a68920cbedd.tar.xz /
ADD cae65dbe2bec0037b36a57f7f32c712c4865daba31b036230aaf200120053e02.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

WORKDIR /var/task

ENTRYPOINT ["/lambda-entrypoint.sh"]

# Copy function code
COPY app.py ${LAMBDA_TASK_ROOT}

# Copy lambda function code and install requirements
COPY . .

# Install the function's dependencies using file requirements.txt
# from your project folder.
COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
ADD . .

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG CB_API_KEY_PROD
ARG BUCKET_DESTINATION

ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV CB_API_KEY_PROD ${CB_API_KEY_PROD}
ENV BUCKET_DESTINATION ${BUCKET_DESTINATION}


# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]